const OpenAI = require('openai');
const fs = require('fs');

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

/**
 * Transcribes vocal response file and evaluates semantic closeness
 * @param {string} audioFilePath - Temp path to uploaded WAV/MP3 recording
 * @param {string} modelAnswer - Expected standard answer generated by AI
 * @returns {Promise<object>} - Transcribed text, alignment score, and feedback text
 */
const transcribeAndEvaluateSpeech = async (audioFilePath, modelAnswer) => {
  try {
    if (!fs.existsSync(audioFilePath)) {
      throw new Error(`Audio target was not found: ${audioFilePath}`);
    }

    let transcript = 'No spoken response detected.';
    
    // In dev without API key, check and fallback
    if (process.env.OPENAI_API_KEY && !process.env.OPENAI_API_KEY.includes('your_openai_api')) {
      const response = await openai.audio.transcriptions.create({
        file: fs.createReadStream(audioFilePath),
        model: 'whisper-1'
      });
      transcript = response.text;
    } else {
      // Return high-fidelity simulation placeholder for demonstration
      transcript = "To maximize search engine optimization and bypass standard ATS parsers, we implement dynamic keyword inclusion by scanning high-frequency word boundaries and injecting them within hidden layouts.";
      console.log('OpenAI API key missing, running high-fidelity interview Whisper mock.');
    }

    // Evaluate alignment score between user answer and target model answer
    const feedbackData = evaluateSemanticAlignment(transcript, modelAnswer);

    return {
      transcript,
      ...feedbackData
    };
  } catch (error) {
    console.error('[Whisper Service Exception]', error.message);
    return {
      transcript: 'Error processing transcription stream.',
      similarityScore: 0,
      feedback: 'Failed to transcribe spoken response. Please verify microphone configuration.'
    };
  }
};

/**
 * Basic word-vector overlap rating representing a fast similarity metric
 */
const evaluateSemanticAlignment = (userText, modelText) => {
  if (!userText || !modelText) {
    return { similarityScore: 0, feedback: 'Insufficient data for semantic alignment.' };
  }

  const clean = (txt) => txt.toLowerCase().match(/\b[a-z]{3,}\b/g) || [];
  const uWords = clean(userText);
  const mWords = clean(modelText);

  const uSet = new Set(uWords);
  const mSet = new Set(mWords);

  // Cosine-like Jaccard coefficient overlap
  const intersection = new Set([...uSet].filter(x => mSet.has(x)));
  const union = new Set([...uSet, ...mSet]);

  const score = Math.round((intersection.size / Math.sqrt(uSet.size * mSet.size || 1)) * 100);
  
  let feedback = '';
  if (score >= 70) {
    feedback = 'Excellent alignment! Your response targets key concepts and uses clear industry-standard keywords.';
  } else if (score >= 40) {
    feedback = 'Moderate match. You addressed core objectives but could integrate more precise technical terminology (e.g. system design trade-offs).';
  } else {
    feedback = 'Weak semantic overlap. Recommendation: Restructure response to answer standard architectural requirements directly.';
  }

  return {
    similarityScore: Math.min(score, 100),
    feedback
  };
};

module.exports = { transcribeAndEvaluateSpeech };
